server:
  port: 8083
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: always

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/pb_catalog
    username: pb
    password: pb
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
        default_schema: catalog
  flyway:
    enabled: true
    schemas: catalog
    default-schema: catalog
