server:
  port: 8081
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: always

pb:
  scheduling:
    hold-minutes: 15 # default hold minutes for SlotReservation

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/pb_scheduling
    username: pb
    password: pb
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
        default_schema: scheduling
  flyway:
    enabled: true
    schemas: scheduling
    default-schema: scheduling
