server:
  port: 8081
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: always

pb:
  scheduling:
    hold-cleanup-interval-ms: 60000
    hold-minutes: 15 # default hold minutes for SlotReservation
    default-duration-minutes_for_zones: 180 # default duration minutes for ZoneReservation
    timezone: Europe/Moscow

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/pb_scheduling
    username: pb
    password: pb
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          time_zone: Europe/Moscow
        default_schema: scheduling
  flyway:
    enabled: true
    schemas: scheduling
    default-schema: scheduling
